apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vulntrack.fullname" . }}-app
  labels:
    {{- include "vulntrack.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "vulntrack.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}"
  JWT_SECRET_KEY: {{ .Values.app.jwtSecretKey | quote }}
  API_KEYS: {{ .Values.app.apiKeys | quote }}
