{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vulntrack.fullname" . }}
  labels:
    {{- include "vulntrack.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vulntrack.fullname" . }}-api
                port:
                  number: 8000
{{- end }}
