apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulntrack.fullname" . }}-postgres
  labels:
    {{- include "vulntrack.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "vulntrack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
