apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vulntrack.fullname" . }}-reports
  labels:
    {{- include "vulntrack.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.app.reportsStorage | quote }}
