apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vulntrack.fullname" . }}-worker
  labels:
    {{- include "vulntrack.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vulntrack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "vulntrack.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  {{- include "vulntrack.selectorLabels" . | nindent 18 }}
                  app.kubernetes.io/component: api
              topologyKey: kubernetes.io/hostname
      containers:
        - name: worker
          image: "{{ .Values.image.worker.repository }}:{{ .Values.image.worker.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "worker.py"]
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "vulntrack.fullname" . }}-config
            - secretRef:
                name: {{ include "vulntrack.fullname" . }}-app
          env:
            - name: PROMETHEUS_MULTIPROC_DIR
              value: ""
            - name: WORKER_METRICS_PORT
              value: {{ .Values.worker.metricsPort | quote }}
            - name: NOTIFY_MIN_SEVERITY
              value: {{ .Values.worker.notifyMinSeverity | quote }}
          livenessProbe:
            exec:
              command: ["python", "-c", "from app.queue import redis_conn; redis_conn.ping()"]
            initialDelaySeconds: 20
            periodSeconds: 30
          volumeMounts:
            - name: reports
              mountPath: /data/reports
            - name: trivy-cache
              mountPath: /data/trivy-cache
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: reports
          persistentVolumeClaim:
            claimName: {{ include "vulntrack.fullname" . }}-reports
        - name: trivy-cache
          persistentVolumeClaim:
            claimName: {{ include "vulntrack.fullname" . }}-trivy-cache
        - name: tmp
          emptyDir: {}
