"""ajout multi-scanner (semgrep, gitleaks) et score EPSS

Revision ID: 093f01725ff6
Revises: d8dc19112edc
Create Date: 2026-08-21 14:25:12.172432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093f01725ff6'
down_revision: Union[str, Sequence[str], None] = 'd8dc19112edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('scanner', sa.String(length=50), server_default='trivy', nullable=False))
    op.add_column('findings', sa.Column('rule_id', sa.String(length=255), nullable=True))
    op.add_column('findings', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('findings', sa.Column('line_number', sa.Integer(), nullable=True))
    op.add_column('findings', sa.Column('epss_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_findings_scanner'), 'findings', ['scanner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_scanner'), table_name='findings')
    op.drop_column('findings', 'epss_score')
    op.drop_column('findings', 'line_number')
    op.drop_column('findings', 'file_path')
    op.drop_column('findings', 'rule_id')
    op.drop_column('findings', 'scanner')
    # ### end Alembic commands ###
