"""notes de triage et audit des findings

Revision ID: bf6cb0806e1d
Revises: 093f01725ff6
Create Date: 2026-08-22 06:35:07.400676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6cb0806e1d'
down_revision: Union[str, Sequence[str], None] = '093f01725ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_notes_finding_id'), 'finding_notes', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_notes_id'), 'finding_notes', ['id'], unique=False)
    op.add_column('findings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'updated_at')
    op.drop_index(op.f('ix_finding_notes_id'), table_name='finding_notes')
    op.drop_index(op.f('ix_finding_notes_finding_id'), table_name='finding_notes')
    op.drop_table('finding_notes')
    # ### end Alembic commands ###
