"""ajout des champs de suivi de scan

Revision ID: c1550ec6428a
Revises: baa47e17b37a
Create Date: 2026-08-16 23:55:11.116747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1550ec6428a'
down_revision: Union[str, Sequence[str], None] = 'baa47e17b37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('raw_report_path', sa.String(length=500), nullable=True))
    op.add_column('scans', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('scans', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scans', sa.Column('findings_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'findings_count')
    op.drop_column('scans', 'finished_at')
    op.drop_column('scans', 'error_message')
    op.drop_column('scans', 'raw_report_path')
    # ### end Alembic commands ###
